### ISSUE TITLE
Userstory 1: Add New Plans

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/capstone_project_fullstack#6]
**As a User**
**I need**
**to be able to**add new plans, 
**So that** I can keep track of my tasks and activities

## Description
Users should have the ability to add new plans to their list of tasks or activities.

## Acceptance Criteria
- [x] Users should see an option to add a new plan.
- [x] Upon clicking the "Add" button, a form or input field should appear for entering the details of the new plan.
- [x] Users should be able to input the description of the plan.
- [x] After entering the plan description, users should be able to save the new plan.
- [x] The newly added plan should be displayed in the list of plans.

## Tasks
- [x] Create a button for adding new plans.
- [x] Implement functionality to show/hide the form for adding new plans.
- [x] Implement functionality to handle user input for the plan description.
- [x] Implement functionality to save the new plan to the backend server.
- [x] Update the UI to display the newly added plan in the list of plans.
